// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OniBus.Api.Persistence;

#nullable disable

namespace OniBus.Api.Persistence.Migrations
{
    [DbContext(typeof(OniBusDbContext))]
    partial class OniBusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OniBus.Domain.Reservas.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("codigo");

                    b.Property<int>("NumeroAssento")
                        .HasColumnType("integer")
                        .HasColumnName("numero_assento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("viagem_id");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_reservas_codigo");

                    b.HasIndex("ViagemId", "NumeroAssento")
                        .IsUnique()
                        .HasDatabaseName("ux_reservas_viagem_assento_confirmada")
                        .HasFilter("status = 'Confirmada'");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("OniBus.Domain.Viagens.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("destino");

                    b.Property<TimeSpan>("DuracaoEstimada")
                        .HasColumnType("interval")
                        .HasColumnName("duracao_estimada");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("origem");

                    b.HasKey("Id");

                    b.HasIndex("Origem", "Destino")
                        .IsUnique()
                        .HasDatabaseName("ux_rotas_origem_destino");

                    b.ToTable("rotas", (string)null);
                });

            modelBuilder.Entity("OniBus.Domain.Viagens.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Partida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("partida");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_base");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid")
                        .HasColumnName("rota_id");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("viagens", (string)null);
                });

            modelBuilder.Entity("OniBus.Domain.Reservas.Reserva", b =>
                {
                    b.HasOne("OniBus.Domain.Viagens.Viagem", null)
                        .WithMany()
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OniBus.Domain.Viagens.Viagem", b =>
                {
                    b.HasOne("OniBus.Domain.Viagens.Rota", null)
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
